# Generated by Django 4.2.8 on 2024-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouble', '0005_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('testing', 'Testing'), ('photo_submission', 'Photo Submission')], default='testing', max_length=100),
        ),
    ]
